"""add anchor_person_id to invitations

Revision ID: 119a820e80a3
Revises: 48c0da84f8ed
Create Date: 2026-08-14 13:15:12.311851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '119a820e80a3'
down_revision: Union[str, None] = '48c0da84f8ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invitations', sa.Column('anchor_person_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'invitations', 'persons', ['anchor_person_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invitations', type_='foreignkey')
    op.drop_column('invitations', 'anchor_person_id')
    # ### end Alembic commands ###
