"""add profile fields to persons

Revision ID: bd7f903cc1eb
Revises: 47dfb72b8131
Create Date: 2026-08-14 13:59:09.762645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd7f903cc1eb'
down_revision: Union[str, None] = '47dfb72b8131'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persons', sa.Column('height_cm', sa.Float(), nullable=True))
    op.add_column('persons', sa.Column('weight_kg', sa.Float(), nullable=True))
    op.add_column('persons', sa.Column('profile_picture_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('persons', 'profile_picture_url')
    op.drop_column('persons', 'weight_kg')
    op.drop_column('persons', 'height_cm')
    # ### end Alembic commands ###
