"""remove anchor_person_id from invitations

Revision ID: f0cefe59c908
Revises: 119a820e80a3
Create Date: 2026-08-14 13:34:12.139553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0cefe59c908'
down_revision: Union[str, None] = '119a820e80a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('invitations_anchor_person_id_fkey', 'invitations', type_='foreignkey')
    op.drop_column('invitations', 'anchor_person_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invitations', sa.Column('anchor_person_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('invitations_anchor_person_id_fkey', 'invitations', 'persons', ['anchor_person_id'], ['id'])
    # ### end Alembic commands ###
